volumes:
  pg_data:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=$NODE_ENV
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $PORT:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
